### PR TITLE
Added support for Definition, DocumentHighlights, FoldingRanges to TextDocumentClient.

### PR DESCRIPTION
**Pull request by ezolotko**
See #170.

### CODE REVIEW

**Comment by david-driscoll** [comment]
@tintoy any input?

**Comment by ezolotko** [comment]
@david-driscoll @tintoy Any resolution on this PR? When this is merged I could try to add Configuration callback request support (similar to TextDocumentClient.Diagnostics.cs but TextDocumentClient.Configuration.cs).

**Comment by ezolotko** [comment]
@david-driscoll @tintoy Any resolution on this PR? Should it be merged?

**Comment by tintoy** [comment]
Sorry! I completely forgot about this one. Will do now :)

**Comment by tintoy** [comment]
Thanks for contributing and sorry for the delay!

**Pull request merged**
