### PR TITLE
Reacting to latest changes for LSP

### PR DESCRIPTION
**Pull request by david-driscoll**
Updated to the latest changes of https://github.com/Microsoft/language-server-protocol.

Also added a few extension methods for logging and such.

### CODE REVIEW

**Comment by david-driscoll** [comment]
@tintoy want to sanity check? 🎉

**Comment by tintoy** [comment]
Hey, nice! Been looking forward to seeing commit characters :)

**Comment by tintoy** [comment]
It looks like the same logging methods are declared in 2 different classes?

**Comment by david-driscoll** [comment]
Theres log methods and show methods, since they're both similar I figured might as well extend both... but yes I didn't rename them all... yay...

**Comment by tintoy** [comment]
Good to have them though :)

**Comment by tintoy** [comment]
BTW, will create a separate issue, but it looks like the server doesn't entirely handle clients that only support static registration of server capabilities. Will put together a repro, but it looks easy to fix :)

**Comment by tintoy** [comment]
> it looks like the server doesn't entirely handle clients that only support static registration of server capabilities

Oops, just realised - I forgot I'd already reported this under #22 :)

**Comment by david-driscoll** [comment]
@tintoy made a small change for that, once builds pass I'll merge and make a new release if you want to try it out.

**Comment by tintoy** [comment]
> made a small change for that, once builds pass I'll merge and make a new release if you want to try it out.

Thanks!

Was just wondering - might it be a little more semantically clear to rely on _matching_ on JSON-RPC method name rather than handler type? The only reason I ask is that (although this is admittedly an edge case) there's nothing to indicate to an API consumer that creating their own handler interface with the correct `[Method]` attribute _will_ correctly handle the messages but _won't_ result in a correct capability declaration.

**Pull request merged**
