### PR TITLE
Added delegate handlers for all base interfaces

### PR DESCRIPTION
**Pull request by david-driscoll**
@tintoy We should now have parity between the client and server in terms of requests / notifications for both sides.  We should look at the client to figure out how best to pull those in.

### CODE REVIEW

**Comment by tintoy** [comment]
Ok - will look into surfacing those APIs on the client next week :)

**Comment by tintoy** [comment]
Nice work on propagating cancellation tokens :)

**Comment by david-driscoll** [comment]
@NTaylorMullen This will involve some (hopefully minor) breaking changes, I'll make the next version number reflect this.  Let me know if you have any concerns, it'll be a few days before I get back to this.

**Comment by NTaylorMullen** [comment]
All good. WIll consume once they're in 😄

**Pull request merged**
