### PR TITLE
Strong naming... yay!!! ... booo!!  (╯°□°）╯︵ ┻━┻

### PR DESCRIPTION
**Pull request by david-driscoll**
* Integrated MediatR as a submodule
  * it won't ever be strong named (see https://github.com/jbogard/MediatR/issues/86)
  * Namespaces are updated on build to differ, so consumes can continue to use MediatR in their related code if they want.

TODOs:
* [x] Add strong name key (.NET Foundation key?)
* [x] Sign assemblies
* [x] Ensure version is pinned for `0.Minor.0.0` (eventually we'll move to `Major.0.0.0`)

### CODE REVIEW

**Comment by david-driscoll** [comment]
cc @NTaylorMullen @tintoy

**Comment by NTaylorMullen** [comment]
This is awesome @david-driscoll! Definitely a pre-req to getting good signing support. I'll ask around about the .NET Foundation key.

**Comment by david-driscoll** [comment]
Fixed #94

**Comment by david-driscoll** [comment]
Appveyor failure is transient sadly.

**Pull request merged**
