### PR TITLE
Set server receiver to `initialized` at the end of the `initialize` request

### LINKED ISSUE #588: Potential race condition with initialized handler
So @rjmholt and I have been debugging an issue with the PowerShell extension after updating to v3.19, and we believe have tracked it down to a race condition. But we don't know if this is an issue with OmniSharp, or maybe even with the LSP spec itself.

We see that the `Initialize` request handler, for LSP2, sets `Initialized`:

https://github.com/OmniSharp/csharp-language-server-protocol/blob/005c87f1c41da3f1b2b35f32c98e3d3132df99a3/src/Server/LanguageServer.cs#L316-L322

This made sense, because `Initialize` was a _request_ and so the client can (and does) wait to hear from the server that `Initialize` was handled. When OmniSharp calls that `initialized()` method (for LSP2) then `GetRequests()` starts behaving "correctly" (handling all notifications and requests):

https://github.com/OmniSharp/csharp-language-server-protocol/blob/1b6788df2600083c28811913a221ccac7b1d72c9/src/Server/LspServerReceiver.cs#L20-L54

But then this was changed for LSP3, we have an `Initialized` (note the D) handler for the `Initialized` _notification_ (which the client cannot wait on). This is problematic because the client then sends more notifications which race the server's handler for the `Initialized` notification, and this race ends up in the requests not being handled, as evidenced by the responses "Unexpected request" and "Unexpected notification" in `GetRequests`.

https://github.com/OmniSharp/csharp-language-server-protocol/blob/005c87f1c41da3f1b2b35f32c98e3d3132df99a3/src/Server/LanguageServer.cs#L327-L337

This correlates with the logs we have when we see a bug in the PowerShell extension:

```
2021-05-06 11:41:07.210 -07:00 [DBG] Finding descriptors for initialize
2021-05-06 11:41:07.382 -07:00 [DBG] Queueing "Serial":initialize:0 request for processing
2021-05-06 11:41:07.428 -07:00 [DBG] Starting: Processing request initialize 0
2021-05-06 11:41:07.444 -07:00 [DBG] Starting: Routing Request (0) initialize
2021-05-06 11:41:08.131 -07:00 [DBG] Finished: Routing Request (0) initialize in 687ms
2021-05-06 11:41:08.131 -07:00 [DBG] Finished: Processing request initialize 0 in 702ms
2021-05-06 11:41:08.211 -07:00 [DBG] Finding descriptors for initialized
2021-05-06 11:41:08.211 -07:00 [DBG] Queueing "Serial":initialized request for processing
2021-05-06 11:41:08.232 -07:00 [WRN] Unexpected notification workspace/didChangeConfiguration {"Method":"workspace/didChangeConfiguration","Params":[[[[[[[[[]],[[]]]],[[]],[[]],[[]],[[]],[[]],[[[[]],[[]]]],[[]],[[]],[[]],[[[[]]]],[[]],[[]],[[[[]],[[]]]],[[[[]],[[]]]],[[[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]]]],[[[[]],[[]],[[]],[[]],[[]]]],[[[[]]]],[[[[]],[[]],[[]],[[]],[[]]]],[[[[]],[[]],[[]]]],[[[[]],[[]]]]]],[[[[[[]]]],[[[[]],[[]],[[]],[[]],[[]]]],[[[[]],[[]]]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[[[]],[[]],[[]],[[]]]],[[]],[[]],[[]],[[]],[[]],[[[[]]]]]],[[[[[[]],[[]],[[]]]],[[]],[[]],[[]],[[]],[[]],[[[[]],[[]],[[null]]]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[[[]],[[]],[[]]]],[[]]]]]]],"TraceParent":null,"TraceState":null,"$type":"Notification"}
2021-05-06 11:41:08.233 -07:00 [WRN] Unexpected request powerShell/getVersion {"Id":1,"Method":"powerShell/getVersion","Params":null,"TraceParent":null,"TraceState":null,"$type":"Request"}
2021-05-06 11:41:08.234 -07:00 [WRN] Tried to send request or notification before initialization was completed and will be sent later {"Id":null,"Error":{"Code":-32002,"Data":null,"Message":"Server Not Initialized","$type":"ErrorMessage"},"Method":"powerShell/getVersion","$type":"ServerNotInitialized"}
2021-05-06 11:41:08.234 -07:00 [DBG] Starting: Processing notification initialized
2021-05-06 11:41:08.243 -07:00 [DBG] Starting: Routing Notification initialized
2021-05-06 11:41:08.366 -07:00 [DBG] Finished: Routing Notification initialized in 132ms
2021-05-06 11:41:08.366 -07:00 [DBG] Finished: Processing notification initialized in 141ms
```

We think this may be related to #556, @david-driscoll was there any update on your investigation into that issue? @majastrz does any of this make sense to you and sound related to your issue?

### PR DESCRIPTION
**Pull request by andschwa**
Resolves #588.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/OmniSharp/csharp-language-server-protocol?pullRequest=589) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/OmniSharp/csharp-language-server-protocol?pullRequest=589) before we can accept your contribution.<br/><br/>:x: andschwa [sign now](https://cla.dotnetfoundation.org/OmniSharp/csharp-language-server-protocol?pullRequest=589)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/OmniSharp/csharp-language-server-protocol?pullRequest=589) it.</sub>

**Comment by andschwa** [comment]
I'm trying to test this locally but haven't managed to get OmniSharp to build yet 😅

**Comment by andschwa** [comment]
@david-driscoll I took the bits built by CI, updated my local build to use them, and can no longer repro my bug! I don't want to say I fixed it too soon, but it sure looks like it. I am about to post a VSIX on my issue so others can confirm, and if so, then I think this will be good to go!

**Comment by andschwa** [comment]
Woo-hoo! @david-driscoll I have multiple users confirming this has completely fixed things.

**Comment by david-driscoll** [comment]
Apparently I had to approve for the ci builds to run... weird.

**Comment by andschwa** [comment]
I'm not sure what to do about the CodeCov part of the build.

**Comment by david-driscoll** [comment]
I'm not worried about 0.02% code coverage drop 😄

**Comment by andschwa** [comment]
This also appears to have resolved @majastrz's issue #556 and @anthony-c-martin's issue #516 🥳

**Pull request merged**
